# Column/data-object names referenced via dplyr/tidyr data-masking (e.g. filter(),
# mutate(), pull()) rather than as actual variables. R CMD check's static analysis
# can't tell these apart from real undefined globals, so they're declared here to
# silence the resulting "no visible binding for global variable" NOTEs.
utils::globalVariables(c(
  "CAS_RN",
  "ENVIRON_COMPARTMENT",
  "ENVIRON_COMPARTMENT_SUB",
  "Long_Name",
  "MEASURED_FLAG",
  "MEASURED_TYPE",
  "MEASURED_UNIT",
  "MEASURED_VALUE",
  "numeric_score",
  "PARAMETER_COMMENT",
  "PARAMETER_NAME",
  "PARAMETER_TYPE",
  "PARAMETER_TYPE_SUB",
  "popular",
  "pretty_name",
  "PROTOCOL_CATEGORY",
  "PROTOCOL_ID",
  "PROTOCOL_NAME",
  "Protocol_Type",
  "REFERENCE_ID",
  "required_recommended",
  "SAMPLE_ID",
  "SAMPLING_DATE",
  "score",
  "Short_Name",
  "SITE_CODE",
  "SPECIES_COMMON_NAME",
  "SPECIES_GROUP",
  "SPECIES_NAME",
  "SUBSAMPLE",
  "title",
  "unique_units",
  "zenodo_licenses"
))
